[[ReferenceBLAS32]]
arch = "aarch64"
git-tree-sha1 = "8c6e0d91a9032c3beeb6b3c4ec0dcfa3250aed12"
libgfortran_version = "5.0.0"
os = "macos"

    [[ReferenceBLAS32.download]]
    sha256 = "ca99b721f0f71898891b11f92fbe0ea17cfd9a0072332518e91af6c1e7fe00f0"
    url = "https://github.com/JuliaBinaryWrappers/ReferenceBLAS32_jll.jl/releases/download/ReferenceBLAS32-v3.12.1+1/ReferenceBLAS32.v3.12.1.aarch64-apple-darwin-libgfortran5.tar.gz"
[[ReferenceBLAS32]]
arch = "aarch64"
git-tree-sha1 = "8ffd89b4650b180f012fc0a59e625eaa0155df9b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[ReferenceBLAS32.download]]
    sha256 = "b066b48ff9de4dc87521e9ec2a7887e66a899f303d66c7f518d3ee1c29ba7233"
    url = "https://github.com/JuliaBinaryWrappers/ReferenceBLAS32_jll.jl/releases/download/ReferenceBLAS32-v3.12.1+1/ReferenceBLAS32.v3.12.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[ReferenceBLAS32]]
arch = "aarch64"
git-tree-sha1 = "04a0a6c284b5edf70685f77a70e2265649297457"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[ReferenceBLAS32.download]]
    sha256 = "ea715a077e2964424439fafc1126afa84271647cf21006870319dfa24da0a8b3"
    url = "https://github.com/JuliaBinaryWrappers/ReferenceBLAS32_jll.jl/releases/download/ReferenceBLAS32-v3.12.1+1/ReferenceBLAS32.v3.12.1.aarch64-linux-musl-libgfortran5.tar.gz"
[[ReferenceBLAS32]]
arch = "aarch64"
git-tree-sha1 = "a642515febeeee79cc52a85f9e017dadd2f52cf4"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[ReferenceBLAS32.download]]
    sha256 = "a3793104f69680329b930eafc51d0e0cd0aa92bdb20033462e8be476bcbe136f"
    url = "https://github.com/JuliaBinaryWrappers/ReferenceBLAS32_jll.jl/releases/download/ReferenceBLAS32-v3.12.1+1/ReferenceBLAS32.v3.12.1.aarch64-unknown-freebsd-libgfortran5.tar.gz"
[[ReferenceBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "784499e265e81b51e1f2d90a557c49ba1f456901"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[ReferenceBLAS32.download]]
    sha256 = "f2dcd990fdcc212b0f3e9bb858e689681b9a28aed6ddbce65420692b3ec452d2"
    url = "https://github.com/JuliaBinaryWrappers/ReferenceBLAS32_jll.jl/releases/download/ReferenceBLAS32-v3.12.1+1/ReferenceBLAS32.v3.12.1.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[ReferenceBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5334479e18ffa0300e2576e75f8c8c2cd5fe2637"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[ReferenceBLAS32.download]]
    sha256 = "e7238de901edaf49b35aa9afcf256cd16d5f89e9a6adc1dfb6cb57bcb9ac7f5a"
    url = "https://github.com/JuliaBinaryWrappers/ReferenceBLAS32_jll.jl/releases/download/ReferenceBLAS32-v3.12.1+1/ReferenceBLAS32.v3.12.1.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[ReferenceBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ecd76ab2b22d7e4367e46c7008909f938d7915b0"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[ReferenceBLAS32.download]]
    sha256 = "5dfaf5d9cb901872f842472a7ca44d2344c45fac7336ad5cffc2fe9fa742e0ad"
    url = "https://github.com/JuliaBinaryWrappers/ReferenceBLAS32_jll.jl/releases/download/ReferenceBLAS32-v3.12.1+1/ReferenceBLAS32.v3.12.1.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[ReferenceBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6d1fed1280b7f74e5c9c2120f25878a1cf284e26"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[ReferenceBLAS32.download]]
    sha256 = "bc0236dd6fb0e69226dd2c8b1a95deae68ce716df3a34b9cf2c558370ba2c0ad"
    url = "https://github.com/JuliaBinaryWrappers/ReferenceBLAS32_jll.jl/releases/download/ReferenceBLAS32-v3.12.1+1/ReferenceBLAS32.v3.12.1.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[ReferenceBLAS32]]
arch = "i686"
git-tree-sha1 = "564ca6bdcdb8482a0986501e8e7408bc14dcfda9"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[ReferenceBLAS32.download]]
    sha256 = "25075dbb305a3ba4e668d995c2ba1a6334cdf1a6202bdf8f798818e1110b0a94"
    url = "https://github.com/JuliaBinaryWrappers/ReferenceBLAS32_jll.jl/releases/download/ReferenceBLAS32-v3.12.1+1/ReferenceBLAS32.v3.12.1.i686-linux-gnu-libgfortran5.tar.gz"
[[ReferenceBLAS32]]
arch = "i686"
git-tree-sha1 = "706745331d74ed8dc79aae34fc1bce60b92e1271"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[ReferenceBLAS32.download]]
    sha256 = "18783f4805544269b921eb0ab79f94f9042b09f60d52d10690a5457d090c6576"
    url = "https://github.com/JuliaBinaryWrappers/ReferenceBLAS32_jll.jl/releases/download/ReferenceBLAS32-v3.12.1+1/ReferenceBLAS32.v3.12.1.i686-linux-musl-libgfortran5.tar.gz"
[[ReferenceBLAS32]]
arch = "i686"
git-tree-sha1 = "9d34567ecbec4d3f03aaa38ddd5111d320f83fae"
libgfortran_version = "5.0.0"
os = "windows"

    [[ReferenceBLAS32.download]]
    sha256 = "58c782f7a432eea3e0d81d91f1d06883b7208f59ea860ed82cea9e1cafccb16a"
    url = "https://github.com/JuliaBinaryWrappers/ReferenceBLAS32_jll.jl/releases/download/ReferenceBLAS32-v3.12.1+1/ReferenceBLAS32.v3.12.1.i686-w64-mingw32-libgfortran5.tar.gz"
[[ReferenceBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "018f2774628c1fe35f6d7f46d6560de4a2879204"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[ReferenceBLAS32.download]]
    sha256 = "dc7e56bc673eda0d85f5f72bc5647b05ff420a94fb60a34b2e6451d4ad247f66"
    url = "https://github.com/JuliaBinaryWrappers/ReferenceBLAS32_jll.jl/releases/download/ReferenceBLAS32-v3.12.1+1/ReferenceBLAS32.v3.12.1.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[ReferenceBLAS32]]
arch = "riscv64"
git-tree-sha1 = "70903e678422222f28748421466a665deb2d2a6e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[ReferenceBLAS32.download]]
    sha256 = "d30ff887f21558a792495b3c7552e7052d0932828cfcc1434a0a4cffb60d0c35"
    url = "https://github.com/JuliaBinaryWrappers/ReferenceBLAS32_jll.jl/releases/download/ReferenceBLAS32-v3.12.1+1/ReferenceBLAS32.v3.12.1.riscv64-linux-gnu-libgfortran5.tar.gz"
[[ReferenceBLAS32]]
arch = "x86_64"
git-tree-sha1 = "acd6dda2a1af9386ec5d611482c73b503992f97d"
libgfortran_version = "5.0.0"
os = "macos"

    [[ReferenceBLAS32.download]]
    sha256 = "b7881c927c9f5a9d844656af1d3b622054cdc9e2cfe8b78154021e86210ab896"
    url = "https://github.com/JuliaBinaryWrappers/ReferenceBLAS32_jll.jl/releases/download/ReferenceBLAS32-v3.12.1+1/ReferenceBLAS32.v3.12.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[ReferenceBLAS32]]
arch = "x86_64"
git-tree-sha1 = "1650fb7aa067cb1364ba2556958e52654d0422a6"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[ReferenceBLAS32.download]]
    sha256 = "769d22ceac00b89c5d1e19dc55ae3785eede7f786515ad77db44540a6eb879ab"
    url = "https://github.com/JuliaBinaryWrappers/ReferenceBLAS32_jll.jl/releases/download/ReferenceBLAS32-v3.12.1+1/ReferenceBLAS32.v3.12.1.x86_64-linux-gnu-libgfortran5.tar.gz"
[[ReferenceBLAS32]]
arch = "x86_64"
git-tree-sha1 = "61362be3d8e39563b9994aef66e674b49c401812"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[ReferenceBLAS32.download]]
    sha256 = "d33cc6cb811584dcbf745587f5dc9c781d23984d34a17a3f3d411085db423640"
    url = "https://github.com/JuliaBinaryWrappers/ReferenceBLAS32_jll.jl/releases/download/ReferenceBLAS32-v3.12.1+1/ReferenceBLAS32.v3.12.1.x86_64-linux-musl-libgfortran5.tar.gz"
[[ReferenceBLAS32]]
arch = "x86_64"
git-tree-sha1 = "da344346a5bcb26602a9a6ab3fa85352c17c9cca"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[ReferenceBLAS32.download]]
    sha256 = "d67b805a860aa3c7970e2f844f9e38c75011b48023ba5893a8376251e634cffe"
    url = "https://github.com/JuliaBinaryWrappers/ReferenceBLAS32_jll.jl/releases/download/ReferenceBLAS32-v3.12.1+1/ReferenceBLAS32.v3.12.1.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[ReferenceBLAS32]]
arch = "x86_64"
git-tree-sha1 = "291211d591ae4e0b074fb0f430f6a7c5287ce719"
libgfortran_version = "5.0.0"
os = "windows"

    [[ReferenceBLAS32.download]]
    sha256 = "8cc9122f7e96819c0341999b9bef0221e8cf318bec915aad5c40deca2e82cbda"
    url = "https://github.com/JuliaBinaryWrappers/ReferenceBLAS32_jll.jl/releases/download/ReferenceBLAS32-v3.12.1+1/ReferenceBLAS32.v3.12.1.x86_64-w64-mingw32-libgfortran5.tar.gz"
